#!/bin/bash

### BEGIN INIT INFO
# Provides:          x10listen
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: X10 listener service
# Description:       Intended to start x10listen.sh on system startup.
### END INIT INFO

SCRIPT='/home/pi/sunrise/scripts/x10listen.sh'
NAME='x10listen'

case "$1" in 
start)
   if [ -e /var/run/$NAME.pid ]; then
      echo $NAME is already running
   else
      $SCRIPT &
      echo $!>/var/run/$NAME.pid
   fi
   ;;
stop)
   pkill -9 -P `cat /var/run/$NAME.pid`
   rm /var/run/$NAME.pid
   ;;
restart)
   $0 stop
   $0 start
   ;;
status)
   if [ -e /var/run/$NAME.pid ]; then
      echo $NAME is running, pid=`cat /var/run/$NAME.pid`
   else
      echo $NAME is NOT running
      exit 1
   fi
   ;;
*)
   echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
